export ZSH="$HOME/.oh-my-zsh"
export PATH="$PATH:/root/bin"

ZSH_THEME="robbyrussell"

plugins=(
    git
    terraform
)

source $ZSH/oh-my-zsh.sh


alias zshup='source /root/.zshrc'
alias rmf='rm -rf'
alias rmtf='rm -rf .terraform .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup'
alias py='python3.9'
alias cmpdel='oci iam compartment delete --compartment-id $(oci iam compartment list --compartment-id $TF_VAR_tenancy_ocid --name "DevOps" --raw-output --query "data[0].id") --force'
alias sshi='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null opc@$(sh get_ip.sh)'
alias ociup='oci setup autocomplete > /dev/null 2>&1'
alias sshup='ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N "" -q'

[[ -e "/root/lib/oci_autocomplete.sh" ]] && source "/root/lib/oci_autocomplete.sh"