export ZSH="$HOME/.oh-my-zsh"
export PATH="$PATH:/root/bin"

ZSH_THEME="robbyrussell"

plugins=(
    git
    terraform
    kubectl
)

source $ZSH/oh-my-zsh.sh


alias zshup='source /root/.zshrc'
alias rmf='rm -rf'
alias sshup='sh /root/resources/ssh.sh'
alias tfrm='rm -rf .terraform .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup'
alias deldev='oci iam compartment delete --compartment-id $(oci iam compartment list --compartment-id $TF_VAR_tenancy_ocid --name "DevOps" --raw-output --query "data[0].id") --force'
alias deloke='oci iam compartment delete --compartment-id $(oci iam compartment list --compartment-id $TF_VAR_tenancy_ocid --name "OKE" --raw-output --query "data[0].id") --force'
